/** Country default currency and cities — generated by scripts/generate-location-data.mjs */
import type { City } from './locations.js';

export interface CountryProfile {
  readonly code: string;
  readonly defaultCurrency: string;
  readonly cities: readonly City[];
}

export const COUNTRY_PROFILES: readonly CountryProfile[] = [
  {
    "code": "AD",
    "defaultCurrency": "EUR",
    "cities": [
      {
        "id": "ad-andorra-la-vella",
        "name": "Andorra la Vella",
        "countryCode": "AD",
        "isCapital": true
      }
    ]
  },
  {
    "code": "AE",
    "defaultCurrency": "AED",
    "cities": [
      {
        "id": "ae-abu-dhabi",
        "name": "Abu Dhabi",
        "countryCode": "AE",
        "isCapital": true
      },
      {
        "id": "ae-dubai",
        "name": "Dubai",
        "countryCode": "AE",
        "isCapital": false
      },
      {
        "id": "ae-sharjah",
        "name": "Sharjah",
        "countryCode": "AE",
        "isCapital": false
      }
    ]
  },
  {
    "code": "AF",
    "defaultCurrency": "AFN",
    "cities": [
      {
        "id": "af-kabul",
        "name": "Kabul",
        "countryCode": "AF",
        "isCapital": true
      }
    ]
  },
  {
    "code": "AG",
    "defaultCurrency": "XCD",
    "cities": [
      {
        "id": "ag-saint-john-s",
        "name": "Saint John's",
        "countryCode": "AG",
        "isCapital": true
      }
    ]
  },
  {
    "code": "AI",
    "defaultCurrency": "XCD",
    "cities": [
      {
        "id": "ai-the-valley",
        "name": "The Valley",
        "countryCode": "AI",
        "isCapital": true
      }
    ]
  },
  {
    "code": "AL",
    "defaultCurrency": "ALL",
    "cities": [
      {
        "id": "al-tirana",
        "name": "Tirana",
        "countryCode": "AL",
        "isCapital": true
      }
    ]
  },
  {
    "code": "AM",
    "defaultCurrency": "AMD",
    "cities": [
      {
        "id": "am-yerevan",
        "name": "Yerevan",
        "countryCode": "AM",
        "isCapital": true
      }
    ]
  },
  {
    "code": "AO",
    "defaultCurrency": "AOA",
    "cities": [
      {
        "id": "ao-luanda",
        "name": "Luanda",
        "countryCode": "AO",
        "isCapital": true
      }
    ]
  },
  {
    "code": "AQ",
    "defaultCurrency": "USD",
    "cities": [
      {
        "id": "aq-mcmurdo-station",
        "name": "McMurdo Station",
        "countryCode": "AQ",
        "isCapital": true
      }
    ]
  },
  {
    "code": "AR",
    "defaultCurrency": "ARS",
    "cities": [
      {
        "id": "ar-buenos-aires",
        "name": "Buenos Aires",
        "countryCode": "AR",
        "isCapital": true
      },
      {
        "id": "ar-cordoba",
        "name": "Córdoba",
        "countryCode": "AR",
        "isCapital": false
      },
      {
        "id": "ar-rosario",
        "name": "Rosario",
        "countryCode": "AR",
        "isCapital": false
      },
      {
        "id": "ar-mendoza",
        "name": "Mendoza",
        "countryCode": "AR",
        "isCapital": false
      }
    ]
  },
  {
    "code": "AS",
    "defaultCurrency": "USD",
    "cities": [
      {
        "id": "as-pago-pago",
        "name": "Pago Pago",
        "countryCode": "AS",
        "isCapital": true
      }
    ]
  },
  {
    "code": "AT",
    "defaultCurrency": "EUR",
    "cities": [
      {
        "id": "at-vienna",
        "name": "Vienna",
        "countryCode": "AT",
        "isCapital": true
      },
      {
        "id": "at-salzburg",
        "name": "Salzburg",
        "countryCode": "AT",
        "isCapital": false
      },
      {
        "id": "at-graz",
        "name": "Graz",
        "countryCode": "AT",
        "isCapital": false
      },
      {
        "id": "at-innsbruck",
        "name": "Innsbruck",
        "countryCode": "AT",
        "isCapital": false
      }
    ]
  },
  {
    "code": "AU",
    "defaultCurrency": "AUD",
    "cities": [
      {
        "id": "au-canberra",
        "name": "Canberra",
        "countryCode": "AU",
        "isCapital": true
      },
      {
        "id": "au-sydney",
        "name": "Sydney",
        "countryCode": "AU",
        "isCapital": false
      },
      {
        "id": "au-melbourne",
        "name": "Melbourne",
        "countryCode": "AU",
        "isCapital": false
      },
      {
        "id": "au-brisbane",
        "name": "Brisbane",
        "countryCode": "AU",
        "isCapital": false
      },
      {
        "id": "au-perth",
        "name": "Perth",
        "countryCode": "AU",
        "isCapital": false
      },
      {
        "id": "au-adelaide",
        "name": "Adelaide",
        "countryCode": "AU",
        "isCapital": false
      }
    ]
  },
  {
    "code": "AW",
    "defaultCurrency": "AWG",
    "cities": [
      {
        "id": "aw-oranjestad",
        "name": "Oranjestad",
        "countryCode": "AW",
        "isCapital": true
      }
    ]
  },
  {
    "code": "AX",
    "defaultCurrency": "EUR",
    "cities": [
      {
        "id": "ax-mariehamn",
        "name": "Mariehamn",
        "countryCode": "AX",
        "isCapital": true
      }
    ]
  },
  {
    "code": "AZ",
    "defaultCurrency": "AZN",
    "cities": [
      {
        "id": "az-baku",
        "name": "Baku",
        "countryCode": "AZ",
        "isCapital": true
      }
    ]
  },
  {
    "code": "BA",
    "defaultCurrency": "BAM",
    "cities": [
      {
        "id": "ba-sarajevo",
        "name": "Sarajevo",
        "countryCode": "BA",
        "isCapital": true
      }
    ]
  },
  {
    "code": "BB",
    "defaultCurrency": "BBD",
    "cities": [
      {
        "id": "bb-bridgetown",
        "name": "Bridgetown",
        "countryCode": "BB",
        "isCapital": true
      }
    ]
  },
  {
    "code": "BD",
    "defaultCurrency": "BDT",
    "cities": [
      {
        "id": "bd-dhaka",
        "name": "Dhaka",
        "countryCode": "BD",
        "isCapital": true
      },
      {
        "id": "bd-chittagong",
        "name": "Chittagong",
        "countryCode": "BD",
        "isCapital": false
      },
      {
        "id": "bd-khulna",
        "name": "Khulna",
        "countryCode": "BD",
        "isCapital": false
      },
      {
        "id": "bd-sylhet",
        "name": "Sylhet",
        "countryCode": "BD",
        "isCapital": false
      }
    ]
  },
  {
    "code": "BE",
    "defaultCurrency": "EUR",
    "cities": [
      {
        "id": "be-brussels",
        "name": "Brussels",
        "countryCode": "BE",
        "isCapital": true
      },
      {
        "id": "be-antwerp",
        "name": "Antwerp",
        "countryCode": "BE",
        "isCapital": false
      },
      {
        "id": "be-ghent",
        "name": "Ghent",
        "countryCode": "BE",
        "isCapital": false
      },
      {
        "id": "be-bruges",
        "name": "Bruges",
        "countryCode": "BE",
        "isCapital": false
      }
    ]
  },
  {
    "code": "BF",
    "defaultCurrency": "XOF",
    "cities": [
      {
        "id": "bf-ouagadougou",
        "name": "Ouagadougou",
        "countryCode": "BF",
        "isCapital": true
      }
    ]
  },
  {
    "code": "BG",
    "defaultCurrency": "BGN",
    "cities": [
      {
        "id": "bg-sofia",
        "name": "Sofia",
        "countryCode": "BG",
        "isCapital": true
      }
    ]
  },
  {
    "code": "BH",
    "defaultCurrency": "BHD",
    "cities": [
      {
        "id": "bh-manama",
        "name": "Manama",
        "countryCode": "BH",
        "isCapital": true
      }
    ]
  },
  {
    "code": "BI",
    "defaultCurrency": "BIF",
    "cities": [
      {
        "id": "bi-gitega",
        "name": "Gitega",
        "countryCode": "BI",
        "isCapital": true
      }
    ]
  },
  {
    "code": "BJ",
    "defaultCurrency": "XOF",
    "cities": [
      {
        "id": "bj-porto-novo",
        "name": "Porto-Novo",
        "countryCode": "BJ",
        "isCapital": true
      }
    ]
  },
  {
    "code": "BL",
    "defaultCurrency": "EUR",
    "cities": [
      {
        "id": "bl-gustavia",
        "name": "Gustavia",
        "countryCode": "BL",
        "isCapital": true
      }
    ]
  },
  {
    "code": "BM",
    "defaultCurrency": "BMD",
    "cities": [
      {
        "id": "bm-hamilton",
        "name": "Hamilton",
        "countryCode": "BM",
        "isCapital": true
      }
    ]
  },
  {
    "code": "BN",
    "defaultCurrency": "BND",
    "cities": [
      {
        "id": "bn-bandar-seri-begawan",
        "name": "Bandar Seri Begawan",
        "countryCode": "BN",
        "isCapital": true
      }
    ]
  },
  {
    "code": "BO",
    "defaultCurrency": "BOB",
    "cities": [
      {
        "id": "bo-sucre",
        "name": "Sucre",
        "countryCode": "BO",
        "isCapital": true
      }
    ]
  },
  {
    "code": "BQ",
    "defaultCurrency": "USD",
    "cities": [
      {
        "id": "bq-kralendijk",
        "name": "Kralendijk",
        "countryCode": "BQ",
        "isCapital": true
      }
    ]
  },
  {
    "code": "BR",
    "defaultCurrency": "BRL",
    "cities": [
      {
        "id": "br-brasilia",
        "name": "Brasília",
        "countryCode": "BR",
        "isCapital": true
      },
      {
        "id": "br-sao-paulo",
        "name": "São Paulo",
        "countryCode": "BR",
        "isCapital": false
      },
      {
        "id": "br-rio-de-janeiro",
        "name": "Rio de Janeiro",
        "countryCode": "BR",
        "isCapital": false
      },
      {
        "id": "br-salvador",
        "name": "Salvador",
        "countryCode": "BR",
        "isCapital": false
      },
      {
        "id": "br-fortaleza",
        "name": "Fortaleza",
        "countryCode": "BR",
        "isCapital": false
      }
    ]
  },
  {
    "code": "BS",
    "defaultCurrency": "BSD",
    "cities": [
      {
        "id": "bs-nassau",
        "name": "Nassau",
        "countryCode": "BS",
        "isCapital": true
      }
    ]
  },
  {
    "code": "BT",
    "defaultCurrency": "BTN",
    "cities": [
      {
        "id": "bt-thimphu",
        "name": "Thimphu",
        "countryCode": "BT",
        "isCapital": true
      }
    ]
  },
  {
    "code": "BV",
    "defaultCurrency": "NOK",
    "cities": [
      {
        "id": "bv-no-permanent-settlement",
        "name": "No permanent settlement",
        "countryCode": "BV",
        "isCapital": true
      }
    ]
  },
  {
    "code": "BW",
    "defaultCurrency": "BWP",
    "cities": [
      {
        "id": "bw-gaborone",
        "name": "Gaborone",
        "countryCode": "BW",
        "isCapital": true
      }
    ]
  },
  {
    "code": "BY",
    "defaultCurrency": "BYN",
    "cities": [
      {
        "id": "by-minsk",
        "name": "Minsk",
        "countryCode": "BY",
        "isCapital": true
      }
    ]
  },
  {
    "code": "BZ",
    "defaultCurrency": "BZD",
    "cities": [
      {
        "id": "bz-belmopan",
        "name": "Belmopan",
        "countryCode": "BZ",
        "isCapital": true
      }
    ]
  },
  {
    "code": "CA",
    "defaultCurrency": "CAD",
    "cities": [
      {
        "id": "ca-ottawa",
        "name": "Ottawa",
        "countryCode": "CA",
        "isCapital": true
      },
      {
        "id": "ca-toronto",
        "name": "Toronto",
        "countryCode": "CA",
        "isCapital": false
      },
      {
        "id": "ca-vancouver",
        "name": "Vancouver",
        "countryCode": "CA",
        "isCapital": false
      },
      {
        "id": "ca-montreal",
        "name": "Montreal",
        "countryCode": "CA",
        "isCapital": false
      },
      {
        "id": "ca-calgary",
        "name": "Calgary",
        "countryCode": "CA",
        "isCapital": false
      },
      {
        "id": "ca-edmonton",
        "name": "Edmonton",
        "countryCode": "CA",
        "isCapital": false
      }
    ]
  },
  {
    "code": "CC",
    "defaultCurrency": "AUD",
    "cities": [
      {
        "id": "cc-west-island",
        "name": "West Island",
        "countryCode": "CC",
        "isCapital": true
      }
    ]
  },
  {
    "code": "CD",
    "defaultCurrency": "CDF",
    "cities": [
      {
        "id": "cd-kinshasa",
        "name": "Kinshasa",
        "countryCode": "CD",
        "isCapital": true
      }
    ]
  },
  {
    "code": "CF",
    "defaultCurrency": "XAF",
    "cities": [
      {
        "id": "cf-bangui",
        "name": "Bangui",
        "countryCode": "CF",
        "isCapital": true
      }
    ]
  },
  {
    "code": "CG",
    "defaultCurrency": "XAF",
    "cities": [
      {
        "id": "cg-brazzaville",
        "name": "Brazzaville",
        "countryCode": "CG",
        "isCapital": true
      }
    ]
  },
  {
    "code": "CH",
    "defaultCurrency": "CHF",
    "cities": [
      {
        "id": "ch-bern",
        "name": "Bern",
        "countryCode": "CH",
        "isCapital": true
      },
      {
        "id": "ch-zurich",
        "name": "Zurich",
        "countryCode": "CH",
        "isCapital": false
      },
      {
        "id": "ch-geneva",
        "name": "Geneva",
        "countryCode": "CH",
        "isCapital": false
      },
      {
        "id": "ch-basel",
        "name": "Basel",
        "countryCode": "CH",
        "isCapital": false
      }
    ]
  },
  {
    "code": "CI",
    "defaultCurrency": "XOF",
    "cities": [
      {
        "id": "ci-yamoussoukro",
        "name": "Yamoussoukro",
        "countryCode": "CI",
        "isCapital": true
      }
    ]
  },
  {
    "code": "CK",
    "defaultCurrency": "NZD",
    "cities": [
      {
        "id": "ck-avarua",
        "name": "Avarua",
        "countryCode": "CK",
        "isCapital": true
      }
    ]
  },
  {
    "code": "CL",
    "defaultCurrency": "CLP",
    "cities": [
      {
        "id": "cl-santiago",
        "name": "Santiago",
        "countryCode": "CL",
        "isCapital": true
      },
      {
        "id": "cl-valparaiso",
        "name": "Valparaíso",
        "countryCode": "CL",
        "isCapital": false
      },
      {
        "id": "cl-concepcion",
        "name": "Concepción",
        "countryCode": "CL",
        "isCapital": false
      }
    ]
  },
  {
    "code": "CM",
    "defaultCurrency": "XAF",
    "cities": [
      {
        "id": "cm-yaounde",
        "name": "Yaoundé",
        "countryCode": "CM",
        "isCapital": true
      }
    ]
  },
  {
    "code": "CN",
    "defaultCurrency": "CNY",
    "cities": [
      {
        "id": "cn-beijing",
        "name": "Beijing",
        "countryCode": "CN",
        "isCapital": true
      },
      {
        "id": "cn-shanghai",
        "name": "Shanghai",
        "countryCode": "CN",
        "isCapital": false
      },
      {
        "id": "cn-guangzhou",
        "name": "Guangzhou",
        "countryCode": "CN",
        "isCapital": false
      },
      {
        "id": "cn-shenzhen",
        "name": "Shenzhen",
        "countryCode": "CN",
        "isCapital": false
      },
      {
        "id": "cn-chengdu",
        "name": "Chengdu",
        "countryCode": "CN",
        "isCapital": false
      },
      {
        "id": "cn-hong-kong",
        "name": "Hong Kong",
        "countryCode": "CN",
        "isCapital": false
      }
    ]
  },
  {
    "code": "CO",
    "defaultCurrency": "COP",
    "cities": [
      {
        "id": "co-bogota",
        "name": "Bogotá",
        "countryCode": "CO",
        "isCapital": true
      },
      {
        "id": "co-medellin",
        "name": "Medellín",
        "countryCode": "CO",
        "isCapital": false
      },
      {
        "id": "co-cali",
        "name": "Cali",
        "countryCode": "CO",
        "isCapital": false
      },
      {
        "id": "co-barranquilla",
        "name": "Barranquilla",
        "countryCode": "CO",
        "isCapital": false
      }
    ]
  },
  {
    "code": "CR",
    "defaultCurrency": "CRC",
    "cities": [
      {
        "id": "cr-san-jose",
        "name": "San José",
        "countryCode": "CR",
        "isCapital": true
      }
    ]
  },
  {
    "code": "CU",
    "defaultCurrency": "CUP",
    "cities": [
      {
        "id": "cu-havana",
        "name": "Havana",
        "countryCode": "CU",
        "isCapital": true
      }
    ]
  },
  {
    "code": "CV",
    "defaultCurrency": "CVE",
    "cities": [
      {
        "id": "cv-praia",
        "name": "Praia",
        "countryCode": "CV",
        "isCapital": true
      }
    ]
  },
  {
    "code": "CW",
    "defaultCurrency": "ANG",
    "cities": [
      {
        "id": "cw-willemstad",
        "name": "Willemstad",
        "countryCode": "CW",
        "isCapital": true
      }
    ]
  },
  {
    "code": "CX",
    "defaultCurrency": "AUD",
    "cities": [
      {
        "id": "cx-flying-fish-cove",
        "name": "Flying Fish Cove",
        "countryCode": "CX",
        "isCapital": true
      }
    ]
  },
  {
    "code": "CY",
    "defaultCurrency": "EUR",
    "cities": [
      {
        "id": "cy-nicosia",
        "name": "Nicosia",
        "countryCode": "CY",
        "isCapital": true
      }
    ]
  },
  {
    "code": "CZ",
    "defaultCurrency": "CZK",
    "cities": [
      {
        "id": "cz-prague",
        "name": "Prague",
        "countryCode": "CZ",
        "isCapital": true
      },
      {
        "id": "cz-brno",
        "name": "Brno",
        "countryCode": "CZ",
        "isCapital": false
      },
      {
        "id": "cz-ostrava",
        "name": "Ostrava",
        "countryCode": "CZ",
        "isCapital": false
      },
      {
        "id": "cz-plzen",
        "name": "Plzeň",
        "countryCode": "CZ",
        "isCapital": false
      }
    ]
  },
  {
    "code": "DE",
    "defaultCurrency": "EUR",
    "cities": [
      {
        "id": "de-berlin",
        "name": "Berlin",
        "countryCode": "DE",
        "isCapital": true
      },
      {
        "id": "de-munich",
        "name": "Munich",
        "countryCode": "DE",
        "isCapital": false
      },
      {
        "id": "de-hamburg",
        "name": "Hamburg",
        "countryCode": "DE",
        "isCapital": false
      },
      {
        "id": "de-frankfurt",
        "name": "Frankfurt",
        "countryCode": "DE",
        "isCapital": false
      },
      {
        "id": "de-cologne",
        "name": "Cologne",
        "countryCode": "DE",
        "isCapital": false
      },
      {
        "id": "de-stuttgart",
        "name": "Stuttgart",
        "countryCode": "DE",
        "isCapital": false
      }
    ]
  },
  {
    "code": "DJ",
    "defaultCurrency": "DJF",
    "cities": [
      {
        "id": "dj-djibouti",
        "name": "Djibouti",
        "countryCode": "DJ",
        "isCapital": true
      }
    ]
  },
  {
    "code": "DK",
    "defaultCurrency": "DKK",
    "cities": [
      {
        "id": "dk-copenhagen",
        "name": "Copenhagen",
        "countryCode": "DK",
        "isCapital": true
      },
      {
        "id": "dk-aarhus",
        "name": "Aarhus",
        "countryCode": "DK",
        "isCapital": false
      },
      {
        "id": "dk-odense",
        "name": "Odense",
        "countryCode": "DK",
        "isCapital": false
      },
      {
        "id": "dk-aalborg",
        "name": "Aalborg",
        "countryCode": "DK",
        "isCapital": false
      }
    ]
  },
  {
    "code": "DM",
    "defaultCurrency": "XCD",
    "cities": [
      {
        "id": "dm-roseau",
        "name": "Roseau",
        "countryCode": "DM",
        "isCapital": true
      }
    ]
  },
  {
    "code": "DO",
    "defaultCurrency": "DOP",
    "cities": [
      {
        "id": "do-santo-domingo",
        "name": "Santo Domingo",
        "countryCode": "DO",
        "isCapital": true
      }
    ]
  },
  {
    "code": "DZ",
    "defaultCurrency": "DZD",
    "cities": [
      {
        "id": "dz-algiers",
        "name": "Algiers",
        "countryCode": "DZ",
        "isCapital": true
      }
    ]
  },
  {
    "code": "EC",
    "defaultCurrency": "USD",
    "cities": [
      {
        "id": "ec-quito",
        "name": "Quito",
        "countryCode": "EC",
        "isCapital": true
      }
    ]
  },
  {
    "code": "EE",
    "defaultCurrency": "EUR",
    "cities": [
      {
        "id": "ee-tallinn",
        "name": "Tallinn",
        "countryCode": "EE",
        "isCapital": true
      }
    ]
  },
  {
    "code": "EG",
    "defaultCurrency": "EGP",
    "cities": [
      {
        "id": "eg-cairo",
        "name": "Cairo",
        "countryCode": "EG",
        "isCapital": true
      },
      {
        "id": "eg-alexandria",
        "name": "Alexandria",
        "countryCode": "EG",
        "isCapital": false
      },
      {
        "id": "eg-giza",
        "name": "Giza",
        "countryCode": "EG",
        "isCapital": false
      },
      {
        "id": "eg-luxor",
        "name": "Luxor",
        "countryCode": "EG",
        "isCapital": false
      }
    ]
  },
  {
    "code": "EH",
    "defaultCurrency": "MAD",
    "cities": [
      {
        "id": "eh-el-aaiun",
        "name": "El Aaiún",
        "countryCode": "EH",
        "isCapital": true
      }
    ]
  },
  {
    "code": "ER",
    "defaultCurrency": "ERN",
    "cities": [
      {
        "id": "er-asmara",
        "name": "Asmara",
        "countryCode": "ER",
        "isCapital": true
      }
    ]
  },
  {
    "code": "ES",
    "defaultCurrency": "EUR",
    "cities": [
      {
        "id": "es-madrid",
        "name": "Madrid",
        "countryCode": "ES",
        "isCapital": true
      },
      {
        "id": "es-barcelona",
        "name": "Barcelona",
        "countryCode": "ES",
        "isCapital": false
      },
      {
        "id": "es-valencia",
        "name": "Valencia",
        "countryCode": "ES",
        "isCapital": false
      },
      {
        "id": "es-seville",
        "name": "Seville",
        "countryCode": "ES",
        "isCapital": false
      },
      {
        "id": "es-bilbao",
        "name": "Bilbao",
        "countryCode": "ES",
        "isCapital": false
      }
    ]
  },
  {
    "code": "ET",
    "defaultCurrency": "ETB",
    "cities": [
      {
        "id": "et-addis-ababa",
        "name": "Addis Ababa",
        "countryCode": "ET",
        "isCapital": true
      },
      {
        "id": "et-dire-dawa",
        "name": "Dire Dawa",
        "countryCode": "ET",
        "isCapital": false
      },
      {
        "id": "et-mekelle",
        "name": "Mekelle",
        "countryCode": "ET",
        "isCapital": false
      }
    ]
  },
  {
    "code": "FI",
    "defaultCurrency": "EUR",
    "cities": [
      {
        "id": "fi-helsinki",
        "name": "Helsinki",
        "countryCode": "FI",
        "isCapital": true
      },
      {
        "id": "fi-tampere",
        "name": "Tampere",
        "countryCode": "FI",
        "isCapital": false
      },
      {
        "id": "fi-turku",
        "name": "Turku",
        "countryCode": "FI",
        "isCapital": false
      },
      {
        "id": "fi-oulu",
        "name": "Oulu",
        "countryCode": "FI",
        "isCapital": false
      }
    ]
  },
  {
    "code": "FJ",
    "defaultCurrency": "FJD",
    "cities": [
      {
        "id": "fj-suva",
        "name": "Suva",
        "countryCode": "FJ",
        "isCapital": true
      }
    ]
  },
  {
    "code": "FK",
    "defaultCurrency": "FKP",
    "cities": [
      {
        "id": "fk-stanley",
        "name": "Stanley",
        "countryCode": "FK",
        "isCapital": true
      }
    ]
  },
  {
    "code": "FM",
    "defaultCurrency": "USD",
    "cities": [
      {
        "id": "fm-palikir",
        "name": "Palikir",
        "countryCode": "FM",
        "isCapital": true
      }
    ]
  },
  {
    "code": "FO",
    "defaultCurrency": "DKK",
    "cities": [
      {
        "id": "fo-torshavn",
        "name": "Tórshavn",
        "countryCode": "FO",
        "isCapital": true
      }
    ]
  },
  {
    "code": "FR",
    "defaultCurrency": "EUR",
    "cities": [
      {
        "id": "fr-paris",
        "name": "Paris",
        "countryCode": "FR",
        "isCapital": true
      },
      {
        "id": "fr-marseille",
        "name": "Marseille",
        "countryCode": "FR",
        "isCapital": false
      },
      {
        "id": "fr-lyon",
        "name": "Lyon",
        "countryCode": "FR",
        "isCapital": false
      },
      {
        "id": "fr-toulouse",
        "name": "Toulouse",
        "countryCode": "FR",
        "isCapital": false
      },
      {
        "id": "fr-nice",
        "name": "Nice",
        "countryCode": "FR",
        "isCapital": false
      },
      {
        "id": "fr-bordeaux",
        "name": "Bordeaux",
        "countryCode": "FR",
        "isCapital": false
      }
    ]
  },
  {
    "code": "GA",
    "defaultCurrency": "XAF",
    "cities": [
      {
        "id": "ga-libreville",
        "name": "Libreville",
        "countryCode": "GA",
        "isCapital": true
      }
    ]
  },
  {
    "code": "GB",
    "defaultCurrency": "GBP",
    "cities": [
      {
        "id": "gb-london",
        "name": "London",
        "countryCode": "GB",
        "isCapital": true
      },
      {
        "id": "gb-manchester",
        "name": "Manchester",
        "countryCode": "GB",
        "isCapital": false
      },
      {
        "id": "gb-birmingham",
        "name": "Birmingham",
        "countryCode": "GB",
        "isCapital": false
      },
      {
        "id": "gb-edinburgh",
        "name": "Edinburgh",
        "countryCode": "GB",
        "isCapital": false
      },
      {
        "id": "gb-glasgow",
        "name": "Glasgow",
        "countryCode": "GB",
        "isCapital": false
      },
      {
        "id": "gb-liverpool",
        "name": "Liverpool",
        "countryCode": "GB",
        "isCapital": false
      },
      {
        "id": "gb-bristol",
        "name": "Bristol",
        "countryCode": "GB",
        "isCapital": false
      }
    ]
  },
  {
    "code": "GD",
    "defaultCurrency": "XCD",
    "cities": [
      {
        "id": "gd-saint-george-s",
        "name": "Saint George's",
        "countryCode": "GD",
        "isCapital": true
      }
    ]
  },
  {
    "code": "GE",
    "defaultCurrency": "GEL",
    "cities": [
      {
        "id": "ge-tbilisi",
        "name": "Tbilisi",
        "countryCode": "GE",
        "isCapital": true
      }
    ]
  },
  {
    "code": "GF",
    "defaultCurrency": "EUR",
    "cities": [
      {
        "id": "gf-cayenne",
        "name": "Cayenne",
        "countryCode": "GF",
        "isCapital": true
      }
    ]
  },
  {
    "code": "GG",
    "defaultCurrency": "GBP",
    "cities": [
      {
        "id": "gg-saint-peter-port",
        "name": "Saint Peter Port",
        "countryCode": "GG",
        "isCapital": true
      }
    ]
  },
  {
    "code": "GH",
    "defaultCurrency": "GHS",
    "cities": [
      {
        "id": "gh-accra",
        "name": "Accra",
        "countryCode": "GH",
        "isCapital": true
      },
      {
        "id": "gh-kumasi",
        "name": "Kumasi",
        "countryCode": "GH",
        "isCapital": false
      },
      {
        "id": "gh-tamale",
        "name": "Tamale",
        "countryCode": "GH",
        "isCapital": false
      }
    ]
  },
  {
    "code": "GI",
    "defaultCurrency": "GIP",
    "cities": [
      {
        "id": "gi-gibraltar",
        "name": "Gibraltar",
        "countryCode": "GI",
        "isCapital": true
      }
    ]
  },
  {
    "code": "GL",
    "defaultCurrency": "DKK",
    "cities": [
      {
        "id": "gl-nuuk",
        "name": "Nuuk",
        "countryCode": "GL",
        "isCapital": true
      }
    ]
  },
  {
    "code": "GM",
    "defaultCurrency": "GMD",
    "cities": [
      {
        "id": "gm-banjul",
        "name": "Banjul",
        "countryCode": "GM",
        "isCapital": true
      }
    ]
  },
  {
    "code": "GN",
    "defaultCurrency": "GNF",
    "cities": [
      {
        "id": "gn-conakry",
        "name": "Conakry",
        "countryCode": "GN",
        "isCapital": true
      }
    ]
  },
  {
    "code": "GP",
    "defaultCurrency": "EUR",
    "cities": [
      {
        "id": "gp-basse-terre",
        "name": "Basse-Terre",
        "countryCode": "GP",
        "isCapital": true
      }
    ]
  },
  {
    "code": "GQ",
    "defaultCurrency": "XAF",
    "cities": [
      {
        "id": "gq-malabo",
        "name": "Malabo",
        "countryCode": "GQ",
        "isCapital": true
      }
    ]
  },
  {
    "code": "GR",
    "defaultCurrency": "EUR",
    "cities": [
      {
        "id": "gr-athens",
        "name": "Athens",
        "countryCode": "GR",
        "isCapital": true
      },
      {
        "id": "gr-thessaloniki",
        "name": "Thessaloniki",
        "countryCode": "GR",
        "isCapital": false
      },
      {
        "id": "gr-patras",
        "name": "Patras",
        "countryCode": "GR",
        "isCapital": false
      },
      {
        "id": "gr-heraklion",
        "name": "Heraklion",
        "countryCode": "GR",
        "isCapital": false
      }
    ]
  },
  {
    "code": "GS",
    "defaultCurrency": "GBP",
    "cities": [
      {
        "id": "gs-king-edward-point",
        "name": "King Edward Point",
        "countryCode": "GS",
        "isCapital": true
      }
    ]
  },
  {
    "code": "GT",
    "defaultCurrency": "GTQ",
    "cities": [
      {
        "id": "gt-guatemala-city",
        "name": "Guatemala City",
        "countryCode": "GT",
        "isCapital": true
      }
    ]
  },
  {
    "code": "GU",
    "defaultCurrency": "USD",
    "cities": [
      {
        "id": "gu-hagatna",
        "name": "Hagåtña",
        "countryCode": "GU",
        "isCapital": true
      }
    ]
  },
  {
    "code": "GW",
    "defaultCurrency": "XOF",
    "cities": [
      {
        "id": "gw-bissau",
        "name": "Bissau",
        "countryCode": "GW",
        "isCapital": true
      }
    ]
  },
  {
    "code": "GY",
    "defaultCurrency": "GYD",
    "cities": [
      {
        "id": "gy-georgetown",
        "name": "Georgetown",
        "countryCode": "GY",
        "isCapital": true
      }
    ]
  },
  {
    "code": "HK",
    "defaultCurrency": "HKD",
    "cities": [
      {
        "id": "hk-hong-kong",
        "name": "Hong Kong",
        "countryCode": "HK",
        "isCapital": true
      },
      {
        "id": "hk-kowloon",
        "name": "Kowloon",
        "countryCode": "HK",
        "isCapital": false
      },
      {
        "id": "hk-sha-tin",
        "name": "Sha Tin",
        "countryCode": "HK",
        "isCapital": false
      }
    ]
  },
  {
    "code": "HM",
    "defaultCurrency": "AUD",
    "cities": [
      {
        "id": "hm-no-permanent-settlement",
        "name": "No permanent settlement",
        "countryCode": "HM",
        "isCapital": true
      }
    ]
  },
  {
    "code": "HN",
    "defaultCurrency": "HNL",
    "cities": [
      {
        "id": "hn-tegucigalpa",
        "name": "Tegucigalpa",
        "countryCode": "HN",
        "isCapital": true
      }
    ]
  },
  {
    "code": "HR",
    "defaultCurrency": "EUR",
    "cities": [
      {
        "id": "hr-zagreb",
        "name": "Zagreb",
        "countryCode": "HR",
        "isCapital": true
      }
    ]
  },
  {
    "code": "HT",
    "defaultCurrency": "HTG",
    "cities": [
      {
        "id": "ht-port-au-prince",
        "name": "Port-au-Prince",
        "countryCode": "HT",
        "isCapital": true
      }
    ]
  },
  {
    "code": "HU",
    "defaultCurrency": "HUF",
    "cities": [
      {
        "id": "hu-budapest",
        "name": "Budapest",
        "countryCode": "HU",
        "isCapital": true
      }
    ]
  },
  {
    "code": "ID",
    "defaultCurrency": "IDR",
    "cities": [
      {
        "id": "id-jakarta",
        "name": "Jakarta",
        "countryCode": "ID",
        "isCapital": true
      },
      {
        "id": "id-surabaya",
        "name": "Surabaya",
        "countryCode": "ID",
        "isCapital": false
      },
      {
        "id": "id-bandung",
        "name": "Bandung",
        "countryCode": "ID",
        "isCapital": false
      },
      {
        "id": "id-medan",
        "name": "Medan",
        "countryCode": "ID",
        "isCapital": false
      },
      {
        "id": "id-bali-denpasar",
        "name": "Bali (Denpasar)",
        "countryCode": "ID",
        "isCapital": false
      }
    ]
  },
  {
    "code": "IE",
    "defaultCurrency": "EUR",
    "cities": [
      {
        "id": "ie-dublin",
        "name": "Dublin",
        "countryCode": "IE",
        "isCapital": true
      },
      {
        "id": "ie-cork",
        "name": "Cork",
        "countryCode": "IE",
        "isCapital": false
      },
      {
        "id": "ie-galway",
        "name": "Galway",
        "countryCode": "IE",
        "isCapital": false
      },
      {
        "id": "ie-limerick",
        "name": "Limerick",
        "countryCode": "IE",
        "isCapital": false
      }
    ]
  },
  {
    "code": "IL",
    "defaultCurrency": "ILS",
    "cities": [
      {
        "id": "il-jerusalem",
        "name": "Jerusalem",
        "countryCode": "IL",
        "isCapital": true
      },
      {
        "id": "il-tel-aviv",
        "name": "Tel Aviv",
        "countryCode": "IL",
        "isCapital": false
      },
      {
        "id": "il-haifa",
        "name": "Haifa",
        "countryCode": "IL",
        "isCapital": false
      },
      {
        "id": "il-beersheba",
        "name": "Beersheba",
        "countryCode": "IL",
        "isCapital": false
      }
    ]
  },
  {
    "code": "IM",
    "defaultCurrency": "GBP",
    "cities": [
      {
        "id": "im-douglas",
        "name": "Douglas",
        "countryCode": "IM",
        "isCapital": true
      }
    ]
  },
  {
    "code": "IN",
    "defaultCurrency": "INR",
    "cities": [
      {
        "id": "in-new-delhi",
        "name": "New Delhi",
        "countryCode": "IN",
        "isCapital": true
      },
      {
        "id": "in-mumbai",
        "name": "Mumbai",
        "countryCode": "IN",
        "isCapital": false
      },
      {
        "id": "in-bangalore",
        "name": "Bangalore",
        "countryCode": "IN",
        "isCapital": false
      },
      {
        "id": "in-chennai",
        "name": "Chennai",
        "countryCode": "IN",
        "isCapital": false
      },
      {
        "id": "in-kolkata",
        "name": "Kolkata",
        "countryCode": "IN",
        "isCapital": false
      },
      {
        "id": "in-hyderabad",
        "name": "Hyderabad",
        "countryCode": "IN",
        "isCapital": false
      },
      {
        "id": "in-pune",
        "name": "Pune",
        "countryCode": "IN",
        "isCapital": false
      }
    ]
  },
  {
    "code": "IO",
    "defaultCurrency": "USD",
    "cities": [
      {
        "id": "io-diego-garcia",
        "name": "Diego Garcia",
        "countryCode": "IO",
        "isCapital": true
      }
    ]
  },
  {
    "code": "IQ",
    "defaultCurrency": "IQD",
    "cities": [
      {
        "id": "iq-baghdad",
        "name": "Baghdad",
        "countryCode": "IQ",
        "isCapital": true
      }
    ]
  },
  {
    "code": "IR",
    "defaultCurrency": "IRR",
    "cities": [
      {
        "id": "ir-tehran",
        "name": "Tehran",
        "countryCode": "IR",
        "isCapital": true
      }
    ]
  },
  {
    "code": "IS",
    "defaultCurrency": "ISK",
    "cities": [
      {
        "id": "is-reykjavik",
        "name": "Reykjavik",
        "countryCode": "IS",
        "isCapital": true
      }
    ]
  },
  {
    "code": "IT",
    "defaultCurrency": "EUR",
    "cities": [
      {
        "id": "it-rome",
        "name": "Rome",
        "countryCode": "IT",
        "isCapital": true
      },
      {
        "id": "it-milan",
        "name": "Milan",
        "countryCode": "IT",
        "isCapital": false
      },
      {
        "id": "it-naples",
        "name": "Naples",
        "countryCode": "IT",
        "isCapital": false
      },
      {
        "id": "it-turin",
        "name": "Turin",
        "countryCode": "IT",
        "isCapital": false
      },
      {
        "id": "it-florence",
        "name": "Florence",
        "countryCode": "IT",
        "isCapital": false
      },
      {
        "id": "it-bologna",
        "name": "Bologna",
        "countryCode": "IT",
        "isCapital": false
      }
    ]
  },
  {
    "code": "JE",
    "defaultCurrency": "GBP",
    "cities": [
      {
        "id": "je-saint-helier",
        "name": "Saint Helier",
        "countryCode": "JE",
        "isCapital": true
      }
    ]
  },
  {
    "code": "JM",
    "defaultCurrency": "JMD",
    "cities": [
      {
        "id": "jm-kingston",
        "name": "Kingston",
        "countryCode": "JM",
        "isCapital": true
      }
    ]
  },
  {
    "code": "JO",
    "defaultCurrency": "JOD",
    "cities": [
      {
        "id": "jo-amman",
        "name": "Amman",
        "countryCode": "JO",
        "isCapital": true
      }
    ]
  },
  {
    "code": "JP",
    "defaultCurrency": "JPY",
    "cities": [
      {
        "id": "jp-tokyo",
        "name": "Tokyo",
        "countryCode": "JP",
        "isCapital": true
      },
      {
        "id": "jp-osaka",
        "name": "Osaka",
        "countryCode": "JP",
        "isCapital": false
      },
      {
        "id": "jp-yokohama",
        "name": "Yokohama",
        "countryCode": "JP",
        "isCapital": false
      },
      {
        "id": "jp-nagoya",
        "name": "Nagoya",
        "countryCode": "JP",
        "isCapital": false
      },
      {
        "id": "jp-sapporo",
        "name": "Sapporo",
        "countryCode": "JP",
        "isCapital": false
      },
      {
        "id": "jp-fukuoka",
        "name": "Fukuoka",
        "countryCode": "JP",
        "isCapital": false
      }
    ]
  },
  {
    "code": "KE",
    "defaultCurrency": "KES",
    "cities": [
      {
        "id": "ke-nairobi",
        "name": "Nairobi",
        "countryCode": "KE",
        "isCapital": true
      },
      {
        "id": "ke-mombasa",
        "name": "Mombasa",
        "countryCode": "KE",
        "isCapital": false
      },
      {
        "id": "ke-kisumu",
        "name": "Kisumu",
        "countryCode": "KE",
        "isCapital": false
      },
      {
        "id": "ke-nakuru",
        "name": "Nakuru",
        "countryCode": "KE",
        "isCapital": false
      }
    ]
  },
  {
    "code": "KG",
    "defaultCurrency": "KGS",
    "cities": [
      {
        "id": "kg-bishkek",
        "name": "Bishkek",
        "countryCode": "KG",
        "isCapital": true
      }
    ]
  },
  {
    "code": "KH",
    "defaultCurrency": "KHR",
    "cities": [
      {
        "id": "kh-phnom-penh",
        "name": "Phnom Penh",
        "countryCode": "KH",
        "isCapital": true
      }
    ]
  },
  {
    "code": "KI",
    "defaultCurrency": "AUD",
    "cities": [
      {
        "id": "ki-tarawa",
        "name": "Tarawa",
        "countryCode": "KI",
        "isCapital": true
      }
    ]
  },
  {
    "code": "KM",
    "defaultCurrency": "KMF",
    "cities": [
      {
        "id": "km-moroni",
        "name": "Moroni",
        "countryCode": "KM",
        "isCapital": true
      }
    ]
  },
  {
    "code": "KN",
    "defaultCurrency": "XCD",
    "cities": [
      {
        "id": "kn-basseterre",
        "name": "Basseterre",
        "countryCode": "KN",
        "isCapital": true
      }
    ]
  },
  {
    "code": "KP",
    "defaultCurrency": "KPW",
    "cities": [
      {
        "id": "kp-pyongyang",
        "name": "Pyongyang",
        "countryCode": "KP",
        "isCapital": true
      }
    ]
  },
  {
    "code": "KR",
    "defaultCurrency": "KRW",
    "cities": [
      {
        "id": "kr-seoul",
        "name": "Seoul",
        "countryCode": "KR",
        "isCapital": true
      },
      {
        "id": "kr-busan",
        "name": "Busan",
        "countryCode": "KR",
        "isCapital": false
      },
      {
        "id": "kr-incheon",
        "name": "Incheon",
        "countryCode": "KR",
        "isCapital": false
      },
      {
        "id": "kr-daegu",
        "name": "Daegu",
        "countryCode": "KR",
        "isCapital": false
      }
    ]
  },
  {
    "code": "KW",
    "defaultCurrency": "KWD",
    "cities": [
      {
        "id": "kw-kuwait-city",
        "name": "Kuwait City",
        "countryCode": "KW",
        "isCapital": true
      }
    ]
  },
  {
    "code": "KY",
    "defaultCurrency": "KYD",
    "cities": [
      {
        "id": "ky-george-town",
        "name": "George Town",
        "countryCode": "KY",
        "isCapital": true
      }
    ]
  },
  {
    "code": "KZ",
    "defaultCurrency": "KZT",
    "cities": [
      {
        "id": "kz-astana",
        "name": "Astana",
        "countryCode": "KZ",
        "isCapital": true
      }
    ]
  },
  {
    "code": "LA",
    "defaultCurrency": "LAK",
    "cities": [
      {
        "id": "la-vientiane",
        "name": "Vientiane",
        "countryCode": "LA",
        "isCapital": true
      }
    ]
  },
  {
    "code": "LB",
    "defaultCurrency": "LBP",
    "cities": [
      {
        "id": "lb-beirut",
        "name": "Beirut",
        "countryCode": "LB",
        "isCapital": true
      }
    ]
  },
  {
    "code": "LC",
    "defaultCurrency": "XCD",
    "cities": [
      {
        "id": "lc-castries",
        "name": "Castries",
        "countryCode": "LC",
        "isCapital": true
      }
    ]
  },
  {
    "code": "LI",
    "defaultCurrency": "CHF",
    "cities": [
      {
        "id": "li-vaduz",
        "name": "Vaduz",
        "countryCode": "LI",
        "isCapital": true
      }
    ]
  },
  {
    "code": "LK",
    "defaultCurrency": "LKR",
    "cities": [
      {
        "id": "lk-sri-jayewardenepura-kotte",
        "name": "Sri Jayewardenepura Kotte",
        "countryCode": "LK",
        "isCapital": true
      }
    ]
  },
  {
    "code": "LR",
    "defaultCurrency": "LRD",
    "cities": [
      {
        "id": "lr-monrovia",
        "name": "Monrovia",
        "countryCode": "LR",
        "isCapital": true
      }
    ]
  },
  {
    "code": "LS",
    "defaultCurrency": "LSL",
    "cities": [
      {
        "id": "ls-maseru",
        "name": "Maseru",
        "countryCode": "LS",
        "isCapital": true
      }
    ]
  },
  {
    "code": "LT",
    "defaultCurrency": "EUR",
    "cities": [
      {
        "id": "lt-vilnius",
        "name": "Vilnius",
        "countryCode": "LT",
        "isCapital": true
      }
    ]
  },
  {
    "code": "LU",
    "defaultCurrency": "EUR",
    "cities": [
      {
        "id": "lu-luxembourg-city",
        "name": "Luxembourg City",
        "countryCode": "LU",
        "isCapital": true
      }
    ]
  },
  {
    "code": "LV",
    "defaultCurrency": "EUR",
    "cities": [
      {
        "id": "lv-riga",
        "name": "Riga",
        "countryCode": "LV",
        "isCapital": true
      }
    ]
  },
  {
    "code": "LY",
    "defaultCurrency": "LYD",
    "cities": [
      {
        "id": "ly-tripoli",
        "name": "Tripoli",
        "countryCode": "LY",
        "isCapital": true
      }
    ]
  },
  {
    "code": "MA",
    "defaultCurrency": "MAD",
    "cities": [
      {
        "id": "ma-rabat",
        "name": "Rabat",
        "countryCode": "MA",
        "isCapital": true
      }
    ]
  },
  {
    "code": "MC",
    "defaultCurrency": "EUR",
    "cities": [
      {
        "id": "mc-monaco",
        "name": "Monaco",
        "countryCode": "MC",
        "isCapital": true
      }
    ]
  },
  {
    "code": "MD",
    "defaultCurrency": "MDL",
    "cities": [
      {
        "id": "md-chisinau",
        "name": "Chișinău",
        "countryCode": "MD",
        "isCapital": true
      }
    ]
  },
  {
    "code": "ME",
    "defaultCurrency": "EUR",
    "cities": [
      {
        "id": "me-podgorica",
        "name": "Podgorica",
        "countryCode": "ME",
        "isCapital": true
      }
    ]
  },
  {
    "code": "MF",
    "defaultCurrency": "EUR",
    "cities": [
      {
        "id": "mf-marigot",
        "name": "Marigot",
        "countryCode": "MF",
        "isCapital": true
      }
    ]
  },
  {
    "code": "MG",
    "defaultCurrency": "MGA",
    "cities": [
      {
        "id": "mg-antananarivo",
        "name": "Antananarivo",
        "countryCode": "MG",
        "isCapital": true
      }
    ]
  },
  {
    "code": "MH",
    "defaultCurrency": "USD",
    "cities": [
      {
        "id": "mh-majuro",
        "name": "Majuro",
        "countryCode": "MH",
        "isCapital": true
      }
    ]
  },
  {
    "code": "MK",
    "defaultCurrency": "MKD",
    "cities": [
      {
        "id": "mk-skopje",
        "name": "Skopje",
        "countryCode": "MK",
        "isCapital": true
      }
    ]
  },
  {
    "code": "ML",
    "defaultCurrency": "XOF",
    "cities": [
      {
        "id": "ml-bamako",
        "name": "Bamako",
        "countryCode": "ML",
        "isCapital": true
      }
    ]
  },
  {
    "code": "MM",
    "defaultCurrency": "MMK",
    "cities": [
      {
        "id": "mm-naypyidaw",
        "name": "Naypyidaw",
        "countryCode": "MM",
        "isCapital": true
      }
    ]
  },
  {
    "code": "MN",
    "defaultCurrency": "MNT",
    "cities": [
      {
        "id": "mn-ulaanbaatar",
        "name": "Ulaanbaatar",
        "countryCode": "MN",
        "isCapital": true
      }
    ]
  },
  {
    "code": "MO",
    "defaultCurrency": "MOP",
    "cities": [
      {
        "id": "mo-macau",
        "name": "Macau",
        "countryCode": "MO",
        "isCapital": true
      }
    ]
  },
  {
    "code": "MP",
    "defaultCurrency": "USD",
    "cities": [
      {
        "id": "mp-saipan",
        "name": "Saipan",
        "countryCode": "MP",
        "isCapital": true
      }
    ]
  },
  {
    "code": "MQ",
    "defaultCurrency": "EUR",
    "cities": [
      {
        "id": "mq-fort-de-france",
        "name": "Fort-de-France",
        "countryCode": "MQ",
        "isCapital": true
      }
    ]
  },
  {
    "code": "MR",
    "defaultCurrency": "MRU",
    "cities": [
      {
        "id": "mr-nouakchott",
        "name": "Nouakchott",
        "countryCode": "MR",
        "isCapital": true
      }
    ]
  },
  {
    "code": "MS",
    "defaultCurrency": "XCD",
    "cities": [
      {
        "id": "ms-plymouth",
        "name": "Plymouth",
        "countryCode": "MS",
        "isCapital": true
      }
    ]
  },
  {
    "code": "MT",
    "defaultCurrency": "EUR",
    "cities": [
      {
        "id": "mt-valletta",
        "name": "Valletta",
        "countryCode": "MT",
        "isCapital": true
      }
    ]
  },
  {
    "code": "MU",
    "defaultCurrency": "MUR",
    "cities": [
      {
        "id": "mu-port-louis",
        "name": "Port Louis",
        "countryCode": "MU",
        "isCapital": true
      }
    ]
  },
  {
    "code": "MV",
    "defaultCurrency": "MVR",
    "cities": [
      {
        "id": "mv-male",
        "name": "Malé",
        "countryCode": "MV",
        "isCapital": true
      }
    ]
  },
  {
    "code": "MW",
    "defaultCurrency": "MWK",
    "cities": [
      {
        "id": "mw-lilongwe",
        "name": "Lilongwe",
        "countryCode": "MW",
        "isCapital": true
      }
    ]
  },
  {
    "code": "MX",
    "defaultCurrency": "MXN",
    "cities": [
      {
        "id": "mx-mexico-city",
        "name": "Mexico City",
        "countryCode": "MX",
        "isCapital": true
      },
      {
        "id": "mx-guadalajara",
        "name": "Guadalajara",
        "countryCode": "MX",
        "isCapital": false
      },
      {
        "id": "mx-monterrey",
        "name": "Monterrey",
        "countryCode": "MX",
        "isCapital": false
      },
      {
        "id": "mx-puebla",
        "name": "Puebla",
        "countryCode": "MX",
        "isCapital": false
      },
      {
        "id": "mx-tijuana",
        "name": "Tijuana",
        "countryCode": "MX",
        "isCapital": false
      }
    ]
  },
  {
    "code": "MY",
    "defaultCurrency": "MYR",
    "cities": [
      {
        "id": "my-kuala-lumpur",
        "name": "Kuala Lumpur",
        "countryCode": "MY",
        "isCapital": true
      },
      {
        "id": "my-penang",
        "name": "Penang",
        "countryCode": "MY",
        "isCapital": false
      },
      {
        "id": "my-johor-bahru",
        "name": "Johor Bahru",
        "countryCode": "MY",
        "isCapital": false
      },
      {
        "id": "my-ipoh",
        "name": "Ipoh",
        "countryCode": "MY",
        "isCapital": false
      }
    ]
  },
  {
    "code": "MZ",
    "defaultCurrency": "MZN",
    "cities": [
      {
        "id": "mz-maputo",
        "name": "Maputo",
        "countryCode": "MZ",
        "isCapital": true
      }
    ]
  },
  {
    "code": "NA",
    "defaultCurrency": "NAD",
    "cities": [
      {
        "id": "na-windhoek",
        "name": "Windhoek",
        "countryCode": "NA",
        "isCapital": true
      }
    ]
  },
  {
    "code": "NC",
    "defaultCurrency": "XPF",
    "cities": [
      {
        "id": "nc-noumea",
        "name": "Nouméa",
        "countryCode": "NC",
        "isCapital": true
      }
    ]
  },
  {
    "code": "NE",
    "defaultCurrency": "XOF",
    "cities": [
      {
        "id": "ne-niamey",
        "name": "Niamey",
        "countryCode": "NE",
        "isCapital": true
      }
    ]
  },
  {
    "code": "NF",
    "defaultCurrency": "AUD",
    "cities": [
      {
        "id": "nf-kingston",
        "name": "Kingston",
        "countryCode": "NF",
        "isCapital": true
      }
    ]
  },
  {
    "code": "NG",
    "defaultCurrency": "NGN",
    "cities": [
      {
        "id": "ng-abuja",
        "name": "Abuja",
        "countryCode": "NG",
        "isCapital": true
      },
      {
        "id": "ng-lagos",
        "name": "Lagos",
        "countryCode": "NG",
        "isCapital": false
      },
      {
        "id": "ng-kano",
        "name": "Kano",
        "countryCode": "NG",
        "isCapital": false
      },
      {
        "id": "ng-ibadan",
        "name": "Ibadan",
        "countryCode": "NG",
        "isCapital": false
      },
      {
        "id": "ng-port-harcourt",
        "name": "Port Harcourt",
        "countryCode": "NG",
        "isCapital": false
      }
    ]
  },
  {
    "code": "NI",
    "defaultCurrency": "NIO",
    "cities": [
      {
        "id": "ni-managua",
        "name": "Managua",
        "countryCode": "NI",
        "isCapital": true
      }
    ]
  },
  {
    "code": "NL",
    "defaultCurrency": "EUR",
    "cities": [
      {
        "id": "nl-amsterdam",
        "name": "Amsterdam",
        "countryCode": "NL",
        "isCapital": true
      },
      {
        "id": "nl-rotterdam",
        "name": "Rotterdam",
        "countryCode": "NL",
        "isCapital": false
      },
      {
        "id": "nl-the-hague",
        "name": "The Hague",
        "countryCode": "NL",
        "isCapital": false
      },
      {
        "id": "nl-utrecht",
        "name": "Utrecht",
        "countryCode": "NL",
        "isCapital": false
      }
    ]
  },
  {
    "code": "NO",
    "defaultCurrency": "NOK",
    "cities": [
      {
        "id": "no-oslo",
        "name": "Oslo",
        "countryCode": "NO",
        "isCapital": true
      },
      {
        "id": "no-bergen",
        "name": "Bergen",
        "countryCode": "NO",
        "isCapital": false
      },
      {
        "id": "no-trondheim",
        "name": "Trondheim",
        "countryCode": "NO",
        "isCapital": false
      },
      {
        "id": "no-stavanger",
        "name": "Stavanger",
        "countryCode": "NO",
        "isCapital": false
      }
    ]
  },
  {
    "code": "NP",
    "defaultCurrency": "NPR",
    "cities": [
      {
        "id": "np-kathmandu",
        "name": "Kathmandu",
        "countryCode": "NP",
        "isCapital": true
      }
    ]
  },
  {
    "code": "NR",
    "defaultCurrency": "AUD",
    "cities": [
      {
        "id": "nr-yaren",
        "name": "Yaren",
        "countryCode": "NR",
        "isCapital": true
      }
    ]
  },
  {
    "code": "NU",
    "defaultCurrency": "NZD",
    "cities": [
      {
        "id": "nu-alofi",
        "name": "Alofi",
        "countryCode": "NU",
        "isCapital": true
      }
    ]
  },
  {
    "code": "NZ",
    "defaultCurrency": "NZD",
    "cities": [
      {
        "id": "nz-wellington",
        "name": "Wellington",
        "countryCode": "NZ",
        "isCapital": true
      },
      {
        "id": "nz-auckland",
        "name": "Auckland",
        "countryCode": "NZ",
        "isCapital": false
      },
      {
        "id": "nz-christchurch",
        "name": "Christchurch",
        "countryCode": "NZ",
        "isCapital": false
      },
      {
        "id": "nz-hamilton",
        "name": "Hamilton",
        "countryCode": "NZ",
        "isCapital": false
      }
    ]
  },
  {
    "code": "OM",
    "defaultCurrency": "OMR",
    "cities": [
      {
        "id": "om-muscat",
        "name": "Muscat",
        "countryCode": "OM",
        "isCapital": true
      }
    ]
  },
  {
    "code": "PA",
    "defaultCurrency": "PAB",
    "cities": [
      {
        "id": "pa-panama-city",
        "name": "Panama City",
        "countryCode": "PA",
        "isCapital": true
      }
    ]
  },
  {
    "code": "PE",
    "defaultCurrency": "PEN",
    "cities": [
      {
        "id": "pe-lima",
        "name": "Lima",
        "countryCode": "PE",
        "isCapital": true
      },
      {
        "id": "pe-arequipa",
        "name": "Arequipa",
        "countryCode": "PE",
        "isCapital": false
      },
      {
        "id": "pe-trujillo",
        "name": "Trujillo",
        "countryCode": "PE",
        "isCapital": false
      },
      {
        "id": "pe-cusco",
        "name": "Cusco",
        "countryCode": "PE",
        "isCapital": false
      }
    ]
  },
  {
    "code": "PF",
    "defaultCurrency": "XPF",
    "cities": [
      {
        "id": "pf-papeete",
        "name": "Papeete",
        "countryCode": "PF",
        "isCapital": true
      }
    ]
  },
  {
    "code": "PG",
    "defaultCurrency": "PGK",
    "cities": [
      {
        "id": "pg-port-moresby",
        "name": "Port Moresby",
        "countryCode": "PG",
        "isCapital": true
      }
    ]
  },
  {
    "code": "PH",
    "defaultCurrency": "PHP",
    "cities": [
      {
        "id": "ph-manila",
        "name": "Manila",
        "countryCode": "PH",
        "isCapital": true
      },
      {
        "id": "ph-cebu-city",
        "name": "Cebu City",
        "countryCode": "PH",
        "isCapital": false
      },
      {
        "id": "ph-davao-city",
        "name": "Davao City",
        "countryCode": "PH",
        "isCapital": false
      },
      {
        "id": "ph-quezon-city",
        "name": "Quezon City",
        "countryCode": "PH",
        "isCapital": false
      }
    ]
  },
  {
    "code": "PK",
    "defaultCurrency": "PKR",
    "cities": [
      {
        "id": "pk-islamabad",
        "name": "Islamabad",
        "countryCode": "PK",
        "isCapital": true
      },
      {
        "id": "pk-karachi",
        "name": "Karachi",
        "countryCode": "PK",
        "isCapital": false
      },
      {
        "id": "pk-lahore",
        "name": "Lahore",
        "countryCode": "PK",
        "isCapital": false
      },
      {
        "id": "pk-faisalabad",
        "name": "Faisalabad",
        "countryCode": "PK",
        "isCapital": false
      }
    ]
  },
  {
    "code": "PL",
    "defaultCurrency": "PLN",
    "cities": [
      {
        "id": "pl-warsaw",
        "name": "Warsaw",
        "countryCode": "PL",
        "isCapital": true
      },
      {
        "id": "pl-krakow",
        "name": "Kraków",
        "countryCode": "PL",
        "isCapital": false
      },
      {
        "id": "pl-wroc-aw",
        "name": "Wrocław",
        "countryCode": "PL",
        "isCapital": false
      },
      {
        "id": "pl-gdansk",
        "name": "Gdańsk",
        "countryCode": "PL",
        "isCapital": false
      },
      {
        "id": "pl-poznan",
        "name": "Poznań",
        "countryCode": "PL",
        "isCapital": false
      }
    ]
  },
  {
    "code": "PM",
    "defaultCurrency": "EUR",
    "cities": [
      {
        "id": "pm-saint-pierre",
        "name": "Saint-Pierre",
        "countryCode": "PM",
        "isCapital": true
      }
    ]
  },
  {
    "code": "PN",
    "defaultCurrency": "NZD",
    "cities": [
      {
        "id": "pn-adamstown",
        "name": "Adamstown",
        "countryCode": "PN",
        "isCapital": true
      }
    ]
  },
  {
    "code": "PR",
    "defaultCurrency": "USD",
    "cities": [
      {
        "id": "pr-san-juan",
        "name": "San Juan",
        "countryCode": "PR",
        "isCapital": true
      }
    ]
  },
  {
    "code": "PS",
    "defaultCurrency": "ILS",
    "cities": [
      {
        "id": "ps-ramallah",
        "name": "Ramallah",
        "countryCode": "PS",
        "isCapital": true
      }
    ]
  },
  {
    "code": "PT",
    "defaultCurrency": "EUR",
    "cities": [
      {
        "id": "pt-lisbon",
        "name": "Lisbon",
        "countryCode": "PT",
        "isCapital": true
      },
      {
        "id": "pt-porto",
        "name": "Porto",
        "countryCode": "PT",
        "isCapital": false
      },
      {
        "id": "pt-faro",
        "name": "Faro",
        "countryCode": "PT",
        "isCapital": false
      },
      {
        "id": "pt-coimbra",
        "name": "Coimbra",
        "countryCode": "PT",
        "isCapital": false
      }
    ]
  },
  {
    "code": "PW",
    "defaultCurrency": "USD",
    "cities": [
      {
        "id": "pw-ngerulmud",
        "name": "Ngerulmud",
        "countryCode": "PW",
        "isCapital": true
      }
    ]
  },
  {
    "code": "PY",
    "defaultCurrency": "PYG",
    "cities": [
      {
        "id": "py-asuncion",
        "name": "Asunción",
        "countryCode": "PY",
        "isCapital": true
      }
    ]
  },
  {
    "code": "QA",
    "defaultCurrency": "QAR",
    "cities": [
      {
        "id": "qa-doha",
        "name": "Doha",
        "countryCode": "QA",
        "isCapital": true
      }
    ]
  },
  {
    "code": "RE",
    "defaultCurrency": "EUR",
    "cities": [
      {
        "id": "re-saint-denis",
        "name": "Saint-Denis",
        "countryCode": "RE",
        "isCapital": true
      }
    ]
  },
  {
    "code": "RO",
    "defaultCurrency": "RON",
    "cities": [
      {
        "id": "ro-bucharest",
        "name": "Bucharest",
        "countryCode": "RO",
        "isCapital": true
      },
      {
        "id": "ro-cluj-napoca",
        "name": "Cluj-Napoca",
        "countryCode": "RO",
        "isCapital": false
      },
      {
        "id": "ro-timisoara",
        "name": "Timișoara",
        "countryCode": "RO",
        "isCapital": false
      },
      {
        "id": "ro-iasi",
        "name": "Iași",
        "countryCode": "RO",
        "isCapital": false
      }
    ]
  },
  {
    "code": "RS",
    "defaultCurrency": "RSD",
    "cities": [
      {
        "id": "rs-belgrade",
        "name": "Belgrade",
        "countryCode": "RS",
        "isCapital": true
      }
    ]
  },
  {
    "code": "RU",
    "defaultCurrency": "RUB",
    "cities": [
      {
        "id": "ru-moscow",
        "name": "Moscow",
        "countryCode": "RU",
        "isCapital": true
      },
      {
        "id": "ru-saint-petersburg",
        "name": "Saint Petersburg",
        "countryCode": "RU",
        "isCapital": false
      },
      {
        "id": "ru-novosibirsk",
        "name": "Novosibirsk",
        "countryCode": "RU",
        "isCapital": false
      },
      {
        "id": "ru-yekaterinburg",
        "name": "Yekaterinburg",
        "countryCode": "RU",
        "isCapital": false
      }
    ]
  },
  {
    "code": "RW",
    "defaultCurrency": "RWF",
    "cities": [
      {
        "id": "rw-kigali",
        "name": "Kigali",
        "countryCode": "RW",
        "isCapital": true
      }
    ]
  },
  {
    "code": "SA",
    "defaultCurrency": "SAR",
    "cities": [
      {
        "id": "sa-riyadh",
        "name": "Riyadh",
        "countryCode": "SA",
        "isCapital": true
      },
      {
        "id": "sa-jeddah",
        "name": "Jeddah",
        "countryCode": "SA",
        "isCapital": false
      },
      {
        "id": "sa-mecca",
        "name": "Mecca",
        "countryCode": "SA",
        "isCapital": false
      },
      {
        "id": "sa-dammam",
        "name": "Dammam",
        "countryCode": "SA",
        "isCapital": false
      }
    ]
  },
  {
    "code": "SB",
    "defaultCurrency": "SBD",
    "cities": [
      {
        "id": "sb-honiara",
        "name": "Honiara",
        "countryCode": "SB",
        "isCapital": true
      }
    ]
  },
  {
    "code": "SC",
    "defaultCurrency": "SCR",
    "cities": [
      {
        "id": "sc-victoria",
        "name": "Victoria",
        "countryCode": "SC",
        "isCapital": true
      }
    ]
  },
  {
    "code": "SD",
    "defaultCurrency": "SDG",
    "cities": [
      {
        "id": "sd-khartoum",
        "name": "Khartoum",
        "countryCode": "SD",
        "isCapital": true
      }
    ]
  },
  {
    "code": "SE",
    "defaultCurrency": "SEK",
    "cities": [
      {
        "id": "se-stockholm",
        "name": "Stockholm",
        "countryCode": "SE",
        "isCapital": true
      },
      {
        "id": "se-gothenburg",
        "name": "Gothenburg",
        "countryCode": "SE",
        "isCapital": false
      },
      {
        "id": "se-malmo",
        "name": "Malmö",
        "countryCode": "SE",
        "isCapital": false
      },
      {
        "id": "se-uppsala",
        "name": "Uppsala",
        "countryCode": "SE",
        "isCapital": false
      }
    ]
  },
  {
    "code": "SG",
    "defaultCurrency": "SGD",
    "cities": [
      {
        "id": "sg-singapore",
        "name": "Singapore",
        "countryCode": "SG",
        "isCapital": true
      },
      {
        "id": "sg-jurong",
        "name": "Jurong",
        "countryCode": "SG",
        "isCapital": false
      },
      {
        "id": "sg-woodlands",
        "name": "Woodlands",
        "countryCode": "SG",
        "isCapital": false
      }
    ]
  },
  {
    "code": "SH",
    "defaultCurrency": "SHP",
    "cities": [
      {
        "id": "sh-jamestown",
        "name": "Jamestown",
        "countryCode": "SH",
        "isCapital": true
      }
    ]
  },
  {
    "code": "SI",
    "defaultCurrency": "EUR",
    "cities": [
      {
        "id": "si-ljubljana",
        "name": "Ljubljana",
        "countryCode": "SI",
        "isCapital": true
      }
    ]
  },
  {
    "code": "SJ",
    "defaultCurrency": "NOK",
    "cities": [
      {
        "id": "sj-longyearbyen",
        "name": "Longyearbyen",
        "countryCode": "SJ",
        "isCapital": true
      }
    ]
  },
  {
    "code": "SK",
    "defaultCurrency": "EUR",
    "cities": [
      {
        "id": "sk-bratislava",
        "name": "Bratislava",
        "countryCode": "SK",
        "isCapital": true
      }
    ]
  },
  {
    "code": "SL",
    "defaultCurrency": "SLE",
    "cities": [
      {
        "id": "sl-freetown",
        "name": "Freetown",
        "countryCode": "SL",
        "isCapital": true
      }
    ]
  },
  {
    "code": "SM",
    "defaultCurrency": "EUR",
    "cities": [
      {
        "id": "sm-san-marino",
        "name": "San Marino",
        "countryCode": "SM",
        "isCapital": true
      }
    ]
  },
  {
    "code": "SN",
    "defaultCurrency": "XOF",
    "cities": [
      {
        "id": "sn-dakar",
        "name": "Dakar",
        "countryCode": "SN",
        "isCapital": true
      }
    ]
  },
  {
    "code": "SO",
    "defaultCurrency": "SOS",
    "cities": [
      {
        "id": "so-mogadishu",
        "name": "Mogadishu",
        "countryCode": "SO",
        "isCapital": true
      }
    ]
  },
  {
    "code": "SR",
    "defaultCurrency": "SRD",
    "cities": [
      {
        "id": "sr-paramaribo",
        "name": "Paramaribo",
        "countryCode": "SR",
        "isCapital": true
      }
    ]
  },
  {
    "code": "SS",
    "defaultCurrency": "SSP",
    "cities": [
      {
        "id": "ss-juba",
        "name": "Juba",
        "countryCode": "SS",
        "isCapital": true
      }
    ]
  },
  {
    "code": "ST",
    "defaultCurrency": "STN",
    "cities": [
      {
        "id": "st-sao-tome",
        "name": "São Tomé",
        "countryCode": "ST",
        "isCapital": true
      }
    ]
  },
  {
    "code": "SV",
    "defaultCurrency": "USD",
    "cities": [
      {
        "id": "sv-san-salvador",
        "name": "San Salvador",
        "countryCode": "SV",
        "isCapital": true
      }
    ]
  },
  {
    "code": "SX",
    "defaultCurrency": "ANG",
    "cities": [
      {
        "id": "sx-philipsburg",
        "name": "Philipsburg",
        "countryCode": "SX",
        "isCapital": true
      }
    ]
  },
  {
    "code": "SY",
    "defaultCurrency": "SYP",
    "cities": [
      {
        "id": "sy-damascus",
        "name": "Damascus",
        "countryCode": "SY",
        "isCapital": true
      }
    ]
  },
  {
    "code": "SZ",
    "defaultCurrency": "SZL",
    "cities": [
      {
        "id": "sz-mbabane",
        "name": "Mbabane",
        "countryCode": "SZ",
        "isCapital": true
      }
    ]
  },
  {
    "code": "TC",
    "defaultCurrency": "USD",
    "cities": [
      {
        "id": "tc-cockburn-town",
        "name": "Cockburn Town",
        "countryCode": "TC",
        "isCapital": true
      }
    ]
  },
  {
    "code": "TD",
    "defaultCurrency": "XAF",
    "cities": [
      {
        "id": "td-n-djamena",
        "name": "N'Djamena",
        "countryCode": "TD",
        "isCapital": true
      }
    ]
  },
  {
    "code": "TF",
    "defaultCurrency": "EUR",
    "cities": [
      {
        "id": "tf-port-aux-francais",
        "name": "Port-aux-Français",
        "countryCode": "TF",
        "isCapital": true
      }
    ]
  },
  {
    "code": "TG",
    "defaultCurrency": "XOF",
    "cities": [
      {
        "id": "tg-lome",
        "name": "Lomé",
        "countryCode": "TG",
        "isCapital": true
      }
    ]
  },
  {
    "code": "TH",
    "defaultCurrency": "THB",
    "cities": [
      {
        "id": "th-bangkok",
        "name": "Bangkok",
        "countryCode": "TH",
        "isCapital": true
      },
      {
        "id": "th-chiang-mai",
        "name": "Chiang Mai",
        "countryCode": "TH",
        "isCapital": false
      },
      {
        "id": "th-phuket",
        "name": "Phuket",
        "countryCode": "TH",
        "isCapital": false
      },
      {
        "id": "th-pattaya",
        "name": "Pattaya",
        "countryCode": "TH",
        "isCapital": false
      }
    ]
  },
  {
    "code": "TJ",
    "defaultCurrency": "TJS",
    "cities": [
      {
        "id": "tj-dushanbe",
        "name": "Dushanbe",
        "countryCode": "TJ",
        "isCapital": true
      }
    ]
  },
  {
    "code": "TK",
    "defaultCurrency": "NZD",
    "cities": [
      {
        "id": "tk-fakaofo",
        "name": "Fakaofo",
        "countryCode": "TK",
        "isCapital": true
      }
    ]
  },
  {
    "code": "TL",
    "defaultCurrency": "USD",
    "cities": [
      {
        "id": "tl-dili",
        "name": "Dili",
        "countryCode": "TL",
        "isCapital": true
      }
    ]
  },
  {
    "code": "TM",
    "defaultCurrency": "TMT",
    "cities": [
      {
        "id": "tm-ashgabat",
        "name": "Ashgabat",
        "countryCode": "TM",
        "isCapital": true
      }
    ]
  },
  {
    "code": "TN",
    "defaultCurrency": "TND",
    "cities": [
      {
        "id": "tn-tunis",
        "name": "Tunis",
        "countryCode": "TN",
        "isCapital": true
      }
    ]
  },
  {
    "code": "TO",
    "defaultCurrency": "TOP",
    "cities": [
      {
        "id": "to-nuku-alofa",
        "name": "Nuku'alofa",
        "countryCode": "TO",
        "isCapital": true
      }
    ]
  },
  {
    "code": "TR",
    "defaultCurrency": "TRY",
    "cities": [
      {
        "id": "tr-ankara",
        "name": "Ankara",
        "countryCode": "TR",
        "isCapital": true
      },
      {
        "id": "tr-istanbul",
        "name": "Istanbul",
        "countryCode": "TR",
        "isCapital": false
      },
      {
        "id": "tr-izmir",
        "name": "Izmir",
        "countryCode": "TR",
        "isCapital": false
      },
      {
        "id": "tr-bursa",
        "name": "Bursa",
        "countryCode": "TR",
        "isCapital": false
      }
    ]
  },
  {
    "code": "TT",
    "defaultCurrency": "TTD",
    "cities": [
      {
        "id": "tt-port-of-spain",
        "name": "Port of Spain",
        "countryCode": "TT",
        "isCapital": true
      }
    ]
  },
  {
    "code": "TV",
    "defaultCurrency": "AUD",
    "cities": [
      {
        "id": "tv-funafuti",
        "name": "Funafuti",
        "countryCode": "TV",
        "isCapital": true
      }
    ]
  },
  {
    "code": "TW",
    "defaultCurrency": "TWD",
    "cities": [
      {
        "id": "tw-taipei",
        "name": "Taipei",
        "countryCode": "TW",
        "isCapital": true
      }
    ]
  },
  {
    "code": "TZ",
    "defaultCurrency": "TZS",
    "cities": [
      {
        "id": "tz-dodoma",
        "name": "Dodoma",
        "countryCode": "TZ",
        "isCapital": true
      }
    ]
  },
  {
    "code": "UA",
    "defaultCurrency": "UAH",
    "cities": [
      {
        "id": "ua-kyiv",
        "name": "Kyiv",
        "countryCode": "UA",
        "isCapital": true
      },
      {
        "id": "ua-lviv",
        "name": "Lviv",
        "countryCode": "UA",
        "isCapital": false
      },
      {
        "id": "ua-odesa",
        "name": "Odesa",
        "countryCode": "UA",
        "isCapital": false
      },
      {
        "id": "ua-kharkiv",
        "name": "Kharkiv",
        "countryCode": "UA",
        "isCapital": false
      },
      {
        "id": "ua-dnipro",
        "name": "Dnipro",
        "countryCode": "UA",
        "isCapital": false
      }
    ]
  },
  {
    "code": "UG",
    "defaultCurrency": "UGX",
    "cities": [
      {
        "id": "ug-kampala",
        "name": "Kampala",
        "countryCode": "UG",
        "isCapital": true
      }
    ]
  },
  {
    "code": "UM",
    "defaultCurrency": "USD",
    "cities": [
      {
        "id": "um-wake-island",
        "name": "Wake Island",
        "countryCode": "UM",
        "isCapital": true
      }
    ]
  },
  {
    "code": "US",
    "defaultCurrency": "USD",
    "cities": [
      {
        "id": "us-washington-d-c",
        "name": "Washington, D.C.",
        "countryCode": "US",
        "isCapital": true
      },
      {
        "id": "us-new-york-city",
        "name": "New York City",
        "countryCode": "US",
        "isCapital": false
      },
      {
        "id": "us-los-angeles",
        "name": "Los Angeles",
        "countryCode": "US",
        "isCapital": false
      },
      {
        "id": "us-chicago",
        "name": "Chicago",
        "countryCode": "US",
        "isCapital": false
      },
      {
        "id": "us-houston",
        "name": "Houston",
        "countryCode": "US",
        "isCapital": false
      },
      {
        "id": "us-san-francisco",
        "name": "San Francisco",
        "countryCode": "US",
        "isCapital": false
      },
      {
        "id": "us-miami",
        "name": "Miami",
        "countryCode": "US",
        "isCapital": false
      },
      {
        "id": "us-seattle",
        "name": "Seattle",
        "countryCode": "US",
        "isCapital": false
      },
      {
        "id": "us-boston",
        "name": "Boston",
        "countryCode": "US",
        "isCapital": false
      },
      {
        "id": "us-dallas",
        "name": "Dallas",
        "countryCode": "US",
        "isCapital": false
      },
      {
        "id": "us-atlanta",
        "name": "Atlanta",
        "countryCode": "US",
        "isCapital": false
      }
    ]
  },
  {
    "code": "UY",
    "defaultCurrency": "UYU",
    "cities": [
      {
        "id": "uy-montevideo",
        "name": "Montevideo",
        "countryCode": "UY",
        "isCapital": true
      }
    ]
  },
  {
    "code": "UZ",
    "defaultCurrency": "UZS",
    "cities": [
      {
        "id": "uz-tashkent",
        "name": "Tashkent",
        "countryCode": "UZ",
        "isCapital": true
      }
    ]
  },
  {
    "code": "VA",
    "defaultCurrency": "EUR",
    "cities": [
      {
        "id": "va-vatican-city",
        "name": "Vatican City",
        "countryCode": "VA",
        "isCapital": true
      }
    ]
  },
  {
    "code": "VC",
    "defaultCurrency": "XCD",
    "cities": [
      {
        "id": "vc-kingstown",
        "name": "Kingstown",
        "countryCode": "VC",
        "isCapital": true
      }
    ]
  },
  {
    "code": "VE",
    "defaultCurrency": "VES",
    "cities": [
      {
        "id": "ve-caracas",
        "name": "Caracas",
        "countryCode": "VE",
        "isCapital": true
      }
    ]
  },
  {
    "code": "VG",
    "defaultCurrency": "USD",
    "cities": [
      {
        "id": "vg-road-town",
        "name": "Road Town",
        "countryCode": "VG",
        "isCapital": true
      }
    ]
  },
  {
    "code": "VI",
    "defaultCurrency": "USD",
    "cities": [
      {
        "id": "vi-charlotte-amalie",
        "name": "Charlotte Amalie",
        "countryCode": "VI",
        "isCapital": true
      }
    ]
  },
  {
    "code": "VN",
    "defaultCurrency": "VND",
    "cities": [
      {
        "id": "vn-hanoi",
        "name": "Hanoi",
        "countryCode": "VN",
        "isCapital": true
      },
      {
        "id": "vn-ho-chi-minh-city",
        "name": "Ho Chi Minh City",
        "countryCode": "VN",
        "isCapital": false
      },
      {
        "id": "vn-da-nang",
        "name": "Da Nang",
        "countryCode": "VN",
        "isCapital": false
      },
      {
        "id": "vn-hai-phong",
        "name": "Hai Phong",
        "countryCode": "VN",
        "isCapital": false
      }
    ]
  },
  {
    "code": "VU",
    "defaultCurrency": "VUV",
    "cities": [
      {
        "id": "vu-port-vila",
        "name": "Port Vila",
        "countryCode": "VU",
        "isCapital": true
      }
    ]
  },
  {
    "code": "WF",
    "defaultCurrency": "XPF",
    "cities": [
      {
        "id": "wf-mata-utu",
        "name": "Mata-Utu",
        "countryCode": "WF",
        "isCapital": true
      }
    ]
  },
  {
    "code": "WS",
    "defaultCurrency": "WST",
    "cities": [
      {
        "id": "ws-apia",
        "name": "Apia",
        "countryCode": "WS",
        "isCapital": true
      }
    ]
  },
  {
    "code": "YE",
    "defaultCurrency": "YER",
    "cities": [
      {
        "id": "ye-sana-a",
        "name": "Sana'a",
        "countryCode": "YE",
        "isCapital": true
      }
    ]
  },
  {
    "code": "YT",
    "defaultCurrency": "EUR",
    "cities": [
      {
        "id": "yt-mamoudzou",
        "name": "Mamoudzou",
        "countryCode": "YT",
        "isCapital": true
      }
    ]
  },
  {
    "code": "ZA",
    "defaultCurrency": "ZAR",
    "cities": [
      {
        "id": "za-pretoria",
        "name": "Pretoria",
        "countryCode": "ZA",
        "isCapital": true
      },
      {
        "id": "za-johannesburg",
        "name": "Johannesburg",
        "countryCode": "ZA",
        "isCapital": false
      },
      {
        "id": "za-cape-town",
        "name": "Cape Town",
        "countryCode": "ZA",
        "isCapital": false
      },
      {
        "id": "za-durban",
        "name": "Durban",
        "countryCode": "ZA",
        "isCapital": false
      },
      {
        "id": "za-port-elizabeth",
        "name": "Port Elizabeth",
        "countryCode": "ZA",
        "isCapital": false
      }
    ]
  },
  {
    "code": "ZM",
    "defaultCurrency": "ZMW",
    "cities": [
      {
        "id": "zm-lusaka",
        "name": "Lusaka",
        "countryCode": "ZM",
        "isCapital": true
      }
    ]
  },
  {
    "code": "ZW",
    "defaultCurrency": "ZWL",
    "cities": [
      {
        "id": "zw-harare",
        "name": "Harare",
        "countryCode": "ZW",
        "isCapital": true
      }
    ]
  }
];

const profileByCode = new Map(COUNTRY_PROFILES.map((profile) => [profile.code, profile]));

export function getCountryProfile(code: string): CountryProfile | undefined {
  return profileByCode.get(code);
}

export function getCitiesForCountry(code: string): readonly City[] {
  return getCountryProfile(code)?.cities ?? [];
}

export function getDefaultCurrencyForCountry(code: string): string {
  return getCountryProfile(code)?.defaultCurrency ?? 'USD';
}
